// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCDTHU_1U52VoDK4eDrjsiUjP7tgZWw6bM',
    appId: '1:885049493387:web:e975c206a1d39841a6518e',
    messagingSenderId: '885049493387',
    projectId: 'bike-house-2a234',
    authDomain: 'bike-house-2a234.firebaseapp.com',
    storageBucket: 'bike-house-2a234.firebasestorage.app',
    measurementId: 'G-4JV4VDTVWQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyATtdKEQcnv9lj--CkoRWHqOZ9ZL-S2LQQ',
    appId: '1:885049493387:android:bba7ab1c2dd5eccda6518e',
    messagingSenderId: '885049493387',
    projectId: 'bike-house-2a234',
    storageBucket: 'bike-house-2a234.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDSsZf9z1nYk_8rP3i_qeZx5xNUNsjeS-s',
    appId: '1:885049493387:ios:8e80d42a9a944af0a6518e',
    messagingSenderId: '885049493387',
    projectId: 'bike-house-2a234',
    storageBucket: 'bike-house-2a234.firebasestorage.app',
    iosBundleId: 'com.example.bikeHouse',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDSsZf9z1nYk_8rP3i_qeZx5xNUNsjeS-s',
    appId: '1:885049493387:ios:8e80d42a9a944af0a6518e',
    messagingSenderId: '885049493387',
    projectId: 'bike-house-2a234',
    storageBucket: 'bike-house-2a234.firebasestorage.app',
    iosBundleId: 'com.example.bikeHouse',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCDTHU_1U52VoDK4eDrjsiUjP7tgZWw6bM',
    appId: '1:885049493387:web:14bb93f0a4c1ea86a6518e',
    messagingSenderId: '885049493387',
    projectId: 'bike-house-2a234',
    authDomain: 'bike-house-2a234.firebaseapp.com',
    storageBucket: 'bike-house-2a234.firebasestorage.app',
    measurementId: 'G-BJXYB7BMNZ',
  );
}
